### ISSUE TITLE
Trino JDBC Driver - Incorrect "Test Connection" Success Despite Invalid Configuration

### ISSUE THREAD

**Issue by krishna-sandeep-alation** [trinodb/trino#25819]
Hi Trino Support Team,

We are currently facing issue with Trino driver that Test connection is passing with invalid configuration.

We observed that the driver returns a successful "Test Connection" even when the JDBC URL (catalog/schema) or username is incorrect, as long as the host is reachable and the password is either correct or not required. This leads to false positives in connection testing — the connection appears successful, but subsequent metadata extraction fails or returns no results.

To reproduce:

Providing an invalid JDBC URL path (e.g., non-existent catalog)

Using an incorrect or non-existent username (with authentication disabled)

Despite these misconfigurations, the driver reports a successful connection. This behaviour is also reproducible via DBeaver.

We have documented this issue internally and would appreciate your guidance on:

Whether this is expected behaviour

Any recommended configuration or future driver changes to improve validation

Please let us know if further details, logs, or reproduction steps are needed. We are happy to assist.

Best regards,
Krishna Sandeep

**Comment by ebyhr** [comment]
What is your Trino version? I expect #24127 improved it.

**Comment by krishna-sandeep-alation** [comment]
I was using v430 but I tried with v475 still seeing same behaviour.

**Comment by ebyhr** [comment]
Did you sepcify `validateConnection` parameter?

**Comment by xsgao-github** [comment]
It's fixed via 7e01309d2e1facc11c5a37df388a3c76318f0c27, released via 469. And yes, you need to specify `validateConnection=true` in JDBC connection properties.

**Comment by krishna-sandeep-alation** [comment]
We are using a Starburst Trino instance with a driver version above v469, but the Test Connection is consistently failing in all cases—even when the host, username, and password are correct.

We have already followed the recommendations provided in [this PR](https://github.com/trinodb/trino/pull/24127), including setting validationConnection=true, but the issue still persists.

Could you please assist us in identifying the root cause or suggest further troubleshooting steps?

**Comment by xsgao-github** [comment]
> Using an incorrect or non-existent username (with authentication disabled)

Trino does not validate credential if authentication is disabled. If authentication is disabled, there is no valid or invalid user, the `X-Trino-User` is ignored. And of course connection will succeed.

> Providing an invalid JDBC URL path (e.g., non-existent catalog)

Catalog/schema set the default catalog/schema to use when an object is not qualified. They are not checked during connecting.

> We are using a Starburst Trino instance with a driver version above v469, but the Test Connection is consistently failing in all cases—even when the host, username, and password are correct.

Please double check your host/port/username/password/etc. Try connect from a browser first. Try to intercept HTTP request from JDBC client to server and see if credential is passed correctly. Look at your authentication provider's log.

**Comment by krishna-sandeep-alation** [comment]
Issue Description:

We are currently encountering a connection failure when attempting to connect to the Trino server. The error message observed is:

`Trino server does not support HEAD /v1/statement`

Even with valid credentials and a correct JDBC URL, the connection test fails when the following JDBC property is set:

`validateConnection = true`

This property internally triggers a HEAD request to the /v1/statement endpoint. As a result, the connection attempt results in an UnsupportedOperationException.

below is the code logic we are using for test connection : 


 ```
private void createConnectionWithUsernamePasswordAuth(String userName, String password)
      throws ConnectionException, SQLException {
    LOGGER.info("Create connection for the user ---->" + userName);
    Driver driver = new TrinoDriver();
    Properties properties = new Properties();
    properties.put(PROP_USER, userName);
    properties.put(PROP_PASSWORD, password);
    properties.put(PROP_VALIDATE_CONNECTION, "true");
    if (this.configuration.useSSL()) {
      addSSLToJDBCProperties(properties);
    }
    try {
      this.connection = driver.connect(getJdbcUri(), properties);
    } catch (SQLException | RuntimeException ex) {
      LOGGER.error("Error during JDBC connection", ex);
      throw new ConnectionException(StarBurstTrinoErrorCode.INVALID_CONNECTION, ex);
    }


    if (this.connection == null) {
      // Since the configuration class validates the JDBC URI,
      // this case is possible in theory, but it should be a programming error
      throw new RuntimeException(StarBurstTrinoErrorCode.NP_CONNECTION.getDescription());
    }
  }
```

can you suggest what could be wrong here ? let me know if anything need from my side.

**Comment by xsgao-github** [comment]
> We are currently encountering a connection failure when attempting to connect to the Trino server. The error message observed is:
Trino server does not support HEAD /v1/statement

You have to upgrade your Trino server.

**Comment by krishna-sandeep-alation** [comment]
We have updated the Trino JDBC driver to the latest version. However, we would like clarification on a few points to proceed further:

1. Do you have any official documentation or guidelines on how to upgrade the Trino server itself (not just the JDBC driver)?

2. Could you please clarify what exactly is referred to as the "Trino server" in this context? Are we expected to update the backend Trino engine, or is this referring to the connector-level integration?

**Comment by krishna-sandeep-alation** [comment]
Just following up on our earlier query regarding the Trino upgrade - https://github.com/trinodb/trino/issues/25819#issuecomment-2948262039

We have already updated the Trino JDBC driver to the latest version. However, we are still seeking clarification on the following points in order to proceed further:

1. Do you have official documentation or guidelines for upgrading the Trino server itself?

2. Can you clarify what exactly is referred to as the "Trino server" in this context? Are we expected to upgrade the Trino engine (i.e., the distributed query engine that runs Trino), or is this in reference to any connector-level integration?

Appreciate your guidance so we can proceed with confidence.
